language: node_js
node_js:
  - "stable"
cache: npm
install:
  - npm ci
script:
  - npm run dev

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on: 
    branch: master
    