language: node_js
node_js:
  - "stable"
cache: npm
install:
  - npm install quick.eco@3.0.0
  - npm install
script:
  - npm run test
deploy:
  provider: pages
  cleanup: true
  github-token: $GITHUB_TOKEN
  on: 
    branch: master